version: 2.1

orbs:
  android: circleci/android@3.0.0
  flutter: circleci/flutter@2.0.0

executors:
  macos-executor:
    macos:
      xcode: "15.2.0" # Wybierz odpowiednią wersję Xcode

  android-executor:
    docker:
    - image: cimg/android:2024.09
    environment:
      ANDROID_HOME: /opt/android/sdk

jobs:
  build_android:
    executor:
      name: android/android_machine
      resource_class: large
      tag: default
    steps:
    - checkout
    - flutter/install_sdk_and_pub:
        version: 3.0.3
    - flutter/install_android_gem
    - run:
        name: Build Android APK
        command: flutter build apk --release
        working_directory: android


workflows:
  version: 2
  build_and_test:
    jobs:
    - build_android
