version: 2.1

orbs:
  android: circleci/android@3.0.0
  flutter: circleci/flutter@2.0.4
  ruby: circleci/ruby@2.2.1

executors:
  macos-executor:
    macos:
      xcode: "15.2.0" # Wybierz odpowiednią wersję Xcode

jobs:
  build_ios:
    executor: macos-executor
    steps:
    - checkout
    - run:
        name: Prepare systems
        command: |
          brew install --cask flutter
          softwareupdate --install-rosetta --agree-to-license
          flutter precache
          gem install ffi -- --enable-libffi-alloc
    - run:
        name: Prepare Flutter
        command: |
          flutter pub get
    - run:
        name: Build iOS IPA
        command: flutter build ipa --no-codesign -t lib/main.dart

  build_android:
    docker:
    - image: cimg/android:2024.10
    steps:
    - checkout
    - flutter/install_sdk_and_pub:
        version: 3.24.3
    - ruby/install:
        version: '3.2.0'
    - run:
        name: Prepare Flutter
        command: |
          apt install openssl
          gem list
          gem install openssl
          gem install fastlane
          gem list
          flutter channel stable
          flutter clean
          flutter upgrade packages
          flutter upgrade
          flutter pub outdated
          flutter doctor -v
          flutter pub get
    - run:
        name: Build Android APK
        command: |
          flutter build apk -t lib/main.dart

workflows:
  version: 2
  build_and_test:
    jobs:
    - build_ios
    - build_android
