version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "15.2.0" # Wybierz odpowiednią wersję Xcode

jobs:
  build:
    executor: macos-executor
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          cd ios
          echo "Install flutter"
          brew install --cask flutter
          echo "Install rbrnv"
          brew update && brew upgrade ruby-build
          rbenv install 3.1.2
          echo "Install rosseta"
          softwareupdate --install-rosetta --agree-to-license
          flutter precache
          gem install ffi -- --enable-libffi-alloc
          echo "Install bundler"
          gem install bundler
          echo "bundle install"
          bundle install
          bundle update
          bundle exec fastlane update_plugins
          bundle exec pod repo update
          flutter doctor
    - run:
        name: Prepare Flutter
        command: |
          flutter clean
          flutter upgrade packages
          flutter upgrade
          flutter doctor -v
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
    - run:
        name: Build iOS IPA
        command: flutter build ipa --no-codesign

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
