version: 2.1

orbs:
  android: circleci/android@2.1.2
  flutter-orb: circleci/flutter@1.1.0
  ruby: circleci/ruby@1.8.0
  macos: circleci/macos@2.3.1

jobs:
  integration_test_ios:
    macos:
      xcode: 15.3.0
    steps:
    - checkout
    - flutter-orb/install_sdk_and_pub:
        flutter_version: 2.10.3
    - flutter-orb/install_ios_pod
    - run:
        name: Integration Test
        command: flutter drive --target=test_driver/app.dart
    - store_artifacts:
        path: ozzie

  distribute_ios:
    macos:
      xcode: 15.3.0
    steps:
    - checkout
    - flutter-orb/install_sdk_and_pub:
        flutter_version: 2.10.3
    - flutter-orb/install_ios_pod
    - ruby/install-deps:
        app-dir: ios
        key: ios
    - run:
        command: bundle exec fastlane distribute_debug
        working_directory: ios

workflows:
  test_and_distribute:
    jobs:
    - flutter-orb/unit_test:
        version: 2.10.3
    - flutter-orb/lint:
        version: 2.10.3
    - integration_test_ios
    - distribute_ios:
        context:
        - mobile
