version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "15.2.0" # Wybierz odpowiednią wersję Xcode

  android-executor:
    docker:
    - image: instrumentisto/flutter:latest

environment:
  ANDROID_HOME: /opt/android/sdk

jobs:
  build_ios:
    executor: macos-executor
    steps:
    - checkout
    - run:
        name: Prepare systems
        command: |
          brew install --cask flutter
          softwareupdate --install-rosetta --agree-to-license
          flutter precache
          gem install ffi -- --enable-libffi-alloc
    - run:
        name: Prepare Flutter
        command: |
          flutter pub get
    - run:
        name: Build iOS IPA
        command: flutter build ipa --no-codesign -t lib/main.dart

  build_android:
    executor: android-executor
    steps:
    - checkout
    - run:
        name: Set up environment
        command: |
          echo 'export ANDROID_HOME=/opt/android/sdk' >> $BASH_ENV
          echo 'export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools' >> $BASH_ENV
          source $BASH_ENV
    - run:
        name: Install dependencies
        command: |
          flutter doctor --android-licenses
          flutter doctor
    - run:
        name: Prepare Flutter
        command: |
          flutter channel stable
          flutter clean
          flutter upgrade packages
          flutter upgrade
          flutter pub outdated
          flutter doctor -v
          flutter pub get
    - run:
        name: build dart app
        command: |
          ls -lah
          dart run build_runner build --delete-conflicting-outputs
    - run:
        name: Build Android APK
        command: flutter build apk --release

workflows:
  version: 2
  build_and_test:
    jobs:
    - build_ios
    - build_android
