version: 2.1

orbs:
  android: circleci/android@3.0.0
  flutter: circleci/flutter@2.0.0

executors:
  macos-executor:
    macos:
      xcode: "15.2.0" # Wybierz odpowiednią wersję Xcode

  android-executor:
    docker:
    - image: cimg/android:2024.09
    environment:
      ANDROID_HOME: /opt/android/sdk

jobs:
  build_android:
    executor:
      name: android/android_machine
      resource_class: large
      tag: default
    steps:
    - flutter/install_sdk_and_pub:
        version: 3.0.3
    - flutter/install_android_gradle_dependencies
    - flutter/install_android_gem
    - run:
        name: Set up environment
        command: |
          echo 'export ANDROID_HOME=/opt/android/sdk' >> $BASH_ENV
          echo 'export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools' >> $BASH_ENV
          source $BASH_ENV
          sdkmanager "platform-tools" "platforms;android-30"
    - run:
        name: Prepare Flutter
        command: |
          flutter channel stable
          flutter clean
          flutter upgrade packages
          flutter upgrade
          flutter pub outdated
          flutter doctor -v
          flutter pub get
    - run:
        name: Build Android APK
        command: flutter build apk --release


workflows:
  version: 2
  build_and_test:
    jobs:
    - build_android
